### ISSUE TITLE
Is it already usable?

### ISSUE THREAD

**Issue by sashaostr** [StatMixedML/CatBoostLSS#1]
Hi Alexander, 
is it already usable? I can't find any code inside - just empty files...

**Comment by StatMixedML** [comment]
Not yet, sorry. It is still VERY developmental and since I can only work on it during my spare time, it might take some time to. Since the last commit, I really hadn`t any chance to bring it into a proper package format. Hope for your understanding

**Comment by sashaostr** [comment]
Sure, understand you completely! I"ll be happy to check it out at the very point you have something to share. I think this project has great importance and be very useful!
