### ISSUE TITLE
Is this forthcoming?

### ISSUE THREAD

**Issue by mik3githubber** [StatMixedML/CatBoostLSS#3]
I know there was some discussion here, in the Catboost and NGBoost repos about this.  Any updates?

**Comment by StatMixedML** [comment]
@mik3githubber Thanks for your comment. Not sure though what you are referencing to?

**Comment by onacrame** [comment]
Sorry I meant is an implementation of this framework coming?  I know there was some discussion about whether it would be implemented directly within CatBoost or as a standalone project.  

This is my main account btw.

**Comment by StatMixedML** [comment]
I am planning to release CatBoostLSS as a standalone project. However, given the current environment we are in, the release might still take some time. Hoping for your understanding.
